=== SiddharthLucky/Tutorials_Parent/Web_Communication/WebCommunication/src/main/resources/Master.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Master" xmlns:tns="http://www.example.org/Master" elementFormDefault="qualified">



    <complexType name="Customer">
    	<sequence>
    		<element name="customerId" type="int"></element>
    		<element name="Name" type="string"></element>
    		<element name="DOB" type="date"></element>
    		<element name="annualSalary" type="int"></element>
    		<element name="address" type="string"></element>
    		<element name="paymentType" type="tns:PaymentType" maxOccurs="2" minOccurs="1"></element>
    	</sequence>
    </complexType>


    <complexType name="PaymentType">
    	<sequence>
    		<element name="cardNumber" type="string"></element>
    		<element name="cardName" type="string"></element>
    		<element name="dateFrom" type="date"></element>
    		<element name="cardType" type="string"></element>
    	</sequence>
    </complexType>


    <element name="Customer" type="tns:Customer"></element>
</schema>

=== SiddharthLucky/Tutorials_Parent/Web_Communication/WebCommunication/src/main/resources/Master.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Customer xmlns:tns="http://www.example.org/Master" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Master Master.xsd ">
  <tns:customerId>0</tns:customerId>
  <tns:Name>tns:Name</tns:Name>
  <tns:DOB>2001-01-01</tns:DOB>
  <tns:annualSalary>0</tns:annualSalary>
  <tns:address>tns:address</tns:address>
  <tns:paymentType>
    <tns:cardNumber>tns:cardNumber</tns:cardNumber>
    <tns:cardName>tns:cardName</tns:cardName>
    <tns:dateFrom>2001-01-01</tns:dateFrom>
    <tns:cardType>tns:cardType</tns:cardType>
  </tns:paymentType>
</tns:Customer>
